create table account (
    id int4 generated by default as identity,
    balance int8, full_name varchar(255),
    password varchar(255),
    phone_number varchar(255),
    role int4,
    username varchar(255),
    primary key (id))